version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  database:
    image: postgres:10.4-alpine
    container_name: kafka-nodejs-example-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
    ports:
      - 8000:5432
    volumes:
      - ./microservico1/database-schemas/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
  producer:
    build: ./microservico1
    container_name: microservico1
    restart: always
    command: sh -c "dockerize -wait tcp://kafka:9092 -wait tcp://database:5432 npm start"
    depends_on:
      - kafka
      - database
    environment:
      PGHOST: database
      PGPORT: 5432
      PGUSER: ${POSTGRES_USER}
      PGDATABASE: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PRODUCER_PORT: ${PRODUCER_PORT}
      DATABASE_USER: alphaone
      DATABASE_HOST: database
      DATABASE_DATABASE: produtos
      DATABASE_PASSWORD: securityisoverrated
      SENTRY_DSN: https://184712bc7fb4485cbe4cd29b4eec9be5@o804873.ingest.sentry.io/5803119
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CONNECT: kafka:9092
    ports:
      - ${PRODUCER_PORT}:${PRODUCER_PORT}
  consumer:
    build: ./microservico2
    container_name: microservico2
    restart: always
    command: sh -c "dockerize -wait tcp://kafka:9092 npm start"
    depends_on:
      - kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CONNECT: kafka:9092
      SLACK_URL: ${SLACK_URL}